implement controller but test failed
[ERROR] com.project.homes.Controller.PropertyControllerTest.testDeleteProperty -- Time elapsed: 0.005 s <<< ERROR!
jakarta.servlet.ServletException: Request processing failed: org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class com.project.homes.entity.Property]

Caused by: org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class com.project.homes.entity.Property]

Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.project.homes.entity.Property` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information